version: "3.2"

services:
  test-evidence-api:
    build:
      context: .
      dockerfile: EvidenceApi.Tests/Dockerfile
    environment:
      - DB_HOST=test-database
      - DB_PORT=3003
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=evidence_api_test
  test-database:
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "3003:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=evidence_api_test
    volumes:
      - ./database:/docker-entrypoint-initdb.d
