// <auto-generated />
using System;
using System.Collections.Generic;
using EvidenceApi.V1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EvidenceApi.Migrations
{
    [DbContext(typeof(EvidenceContext))]
    [Migration("20201209135358_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EvidenceApi.V1.Infrastructure.EvidenceRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<List<string>>("DeliveryMethods")
                        .HasColumnName("delivery_methods")
                        .HasColumnType("text[]");

                    b.Property<List<string>>("DocumentTypes")
                        .HasColumnName("document_types")
                        .HasColumnType("text[]");

                    b.Property<Guid>("ResidentId")
                        .HasColumnName("resident_id")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceRequestedBy")
                        .HasColumnName("service_requested_by")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("evidence_request");
                });

            modelBuilder.Entity("EvidenceApi.V1.Infrastructure.ResidentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("phone_number")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("resident");
                });
#pragma warning restore 612, 618
        }
    }
}
