version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.9
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-python:
    docker:
      - image: circleci/python:3.7
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  deploy-lambda:
    description: "Deploys API via Serverless"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_13.x | bash -
            apt-get update && apt-get install -y nodejs
      - run:
          name: Install serverless CLI
          command: npm i -g serverless
      - run:
          name: Build lambda
          command: |
            cd ./EvidenceApi/
            chmod +x ./build.sh
            ./build.sh
      - run:
          name: Deploy lambda
          command: |
            cd ./EvidenceApi/
            sls deploy --stage <<parameters.stage>> --conceal
  publish-to-swaggerhub:
    description: "Publishes API docs to SwaggerHub"
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | bash -
            apt-get update && apt-get install -y nodejs
      - run:
          name: Install SwaggerHub CLI
          command: npm i -g swaggerhub-cli
      - run:
          name: Publish to SwaggerHub
          command: |
            cd ./EvidenceApi/
            chmod +x ./publish-to-swagger-hub.sh
            ./publish-to-swagger-hub.sh

  migrate-database:
    description: "Migrate database"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install Unzip
          command: apt-get update && apt-get install unzip
      - run:
          name: Install AWS CLI
          command: |
            curl -L -o awscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
            unzip awscliv2.zip
            ./aws/install
      - run:
          name: Install Session Manager plugin
          command: |
            curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
            dpkg -i session-manager-plugin.deb
      - run:
          name: Install dotnet ef core
          command: dotnet tool install dotnet-ef --tool-path ./dotnet-ef-local/
      - run:
          name: SSH into RDS and migrate database
          command: |
            aws ssm get-parameter --name "/document-evidence-store-<<parameters.stage>>-jump-box-pem-key" --output text --query Parameter.Value > ./private-key.pem
            chmod 400 ./private-key.pem
            HOST=$(aws ssm get-parameter --name /evidence-api/<<parameters.stage>>/postgres-hostname --query Parameter.Value)
            PORT=$(aws ssm get-parameter --name /evidence-api/<<parameters.stage>>/postgres-port --query Parameter.Value)
            INSTANCE_NAME=$(aws ssm get-parameter --name /document-evidence-store-<<parameters.stage>>-jump-box-instance-name --query Parameter.Value)
            ssh -4 -i ./private-key.pem -Nf -M -L ${PORT//\"}:${HOST//\"}:${PORT//\"} -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o ProxyCommand="aws ssm start-session --target %h --document AWS-StartSSHSession --parameters portNumber=%p --region=eu-west-2" ec2-user@${INSTANCE_NAME//\"}
            PASSWORD=$(aws ssm get-parameter --name /evidence-api/<<parameters.stage>>/postgres-password --query Parameter.Value --with-decryption)
            USERNAME=$(aws ssm get-parameter --name /evidence-api/<<parameters.stage>>/postgres-username --query Parameter.Value)
            DATABASE=$(aws ssm get-parameter --name /evidence-api/<<parameters.stage>>/postgres-database --query Parameter.Value)
            CONN_STR="Host=localhost;Password=${PASSWORD};Port=${PORT};Username=${USERNAME};Database=${DATABASE}"
            cd ./EvidenceApi/
            CONNECTION_STRING=${CONN_STR} ./../dotnet-ef-local/dotnet-ef database update

jobs:
  check-code-formatting:
    executor: docker-dotnet
    steps:
      - checkout
      - run:
          name: Install dotnet format
          command: dotnet tool install dotnet-format --tool-path ./dotnet-format-local/
      - run:
          name: Run formatter check
          command: ./dotnet-format-local/dotnet-format --check

  build-and-test:
    executor: docker-python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker-compose build evidence-api-test
      - run:
          name: Run tests
          command: docker-compose run evidence-api-test

  assume-role-staging:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_STAGING
  assume-role-production:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_PRODUCTION

  deploy-to-staging:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "staging"

  deploy-to-production:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "production"

  migrate-database-staging:
    executor: docker-dotnet
    steps:
      - migrate-database:
          stage: "staging"

  migrate-database-production:
    executor: docker-dotnet
    steps:
      - migrate-database:
          stage: "production"

  publish-to-swaggerhub:
    executor: docker-dotnet
    steps:
      - publish-to-swaggerhub

  owasp-zap-baseline-scan:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - *attach_workspace

      # - run: 
      #     name: Add the Microsoft package signing key to your list of trusted keys
      #     command: |
      #       wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      #       sudo dpkg -i packages-microsoft-prod.deb
      #       rm packages-microsoft-prod.deb
      # - run: 
      #     name: Intall dotnet
      #     command: |
      #       sudo apt-get update; \
      #       sudo apt-get install -y apt-transport-https && \
      #       sudo apt-get update && \
      #       sudo apt-get install -y dotnet-sdk-5.0
      - run: 
          name: dotnet dependencies
          command: |
            apt-get update \
            && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            ca-certificates \
             \
            libc6 \
            libgcc1 \
            libgssapi-krb5-2 \
            libicu66 \
            libssl1.1 \
            libstdc++6 \
            zlib1g \
            && rm -rf /var/lib/apt/lists/*
      - run:
          name: install dotnet
          comand: |
            curl -SL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Runtime/$DOTNET_VERSION/dotnet-runtime-$DOTNET_VERSION-linux-x64.tar.gz \
            && dotnet_sha512='d4d67df5ff5f6dde0d865a6e87559955bd57429df396cf7d05fe77f09e6220c67dc5e66439b1801ca4d301a62f81f666122bf4b623b31a46b861677dcafc62a4' \
            && echo "$dotnet_sha512 dotnet.tar.gz" | sha512sum -c - \
            && mkdir -p /usr/share/dotnet \
            && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
            && rm dotnet.tar.gz \
            && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

      - run:
          name: Run application in background
          command: dotnet run --project EvidenceApi
          background: true

      - run:
          name: Pull owasp zap docker image
          command: docker pull owasp/zap2docker-stable:2.10.0

      - run:
          name: ZAP baseline test of application
          # It will exit with codes of:
          # 0: Success
          # 1: At least 1 FAIL
          # 2: At least one WARN and no FAILs
          # 3: Any other failure
          # Link to above:https://github.com/zaproxy/zaproxy/blob/main/docker/zap-baseline.py#L31-L35
          command: |
              (
                docker run -t owasp/zap2docker-stable:2.10.0 zap-baseline.py \
                -j \
                -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}/zap-baseline.conf \
                -t http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):3000 || \
                if [[ $? == 0 || $? == 2 ]]; then exit 0; else exit 1; fi;
              )



workflows:
  check-and-deploy-staging-and-production:
    jobs:
      # Build & Test
      - check-code-formatting
      - build-and-test
      # OWASP check
      - owasp-zap-baseline-scan:
          requires:
            - build-and-test
      # Staging deploy
      - assume-role-staging:
          context: api-assume-role-document-evidence-store-staging-context
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
      - migrate-database-staging:
          requires:
            - assume-role-staging
      - deploy-to-staging:
          requires:
            - migrate-database-staging
            - owasp-zap-baseline-scan

      # Production deploy
      - permit-production-release:
          type: approval
          requires:
            - deploy-to-staging
      - assume-role-production:
          context: api-assume-role-document-evidence-store-production-context
          requires:
            - permit-production-release
      - migrate-database-production:
          requires:
            - assume-role-production
      - deploy-to-production:
          requires:
            - migrate-database-production
      - publish-to-swaggerhub:
          context: api-assume-role-document-evidence-store-production-context
          requires:
            - deploy-to-production
