@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.2.0/C4_Deployment.puml
!include https://raw.githubusercontent.com/LBHackney-IT/cv-19-res-support-v3/development/docs/diagrams/c4_shared.puml

title Document Evidence Store Document Retrieval Sequence Flow Diagram

Service -> DocumentsAPI: POST /claims/:claimId/download_links
Service <- DocumentsAPI: S3 presigned download URL
Service -> S3: GET S3 presigned download URL

@enduml
