services:
  test:
    build:
      context: ../
      dockerfile: ./EvidenceApi.Tests/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=evidence_api
    depends_on:
      migrate:
        condition: service_completed_successfully

  migrate:
    extends:
      file: ../database/compose.yml
      service: migrate
    depends_on:
      db:
        condition: service_healthy

  db:
    extends:
      file: ../database/compose.yml
      service: db
